### ISSUE TITLE
Przygotowanie bazy danych

### ISSUE THREAD

**Issue by KDworak** [KDworak/ZI#1]
Time needed to do : (1H)

**Comment by KDworak** [comment]
Time needed to do : (1H)

**Comment by Bl0tniaQus** [comment]
![Image](https://github.com/user-attachments/assets/ec4b0baa-1931-4d95-928d-dad68c932656)

MongoDB Cloud
email: elektrotechnika1945@gmail.com
hasło: zaq1@WSX

użytkownik dostępowy do bazy:
nazwa: zi_projekt
hasło: L7izN7BEN59yVoN1
