### ISSUE TITLE
Sporządzenie dokumentacji

### ISSUE THREAD

**Issue by KDworak** [KDworak/ZI#31]
Time needed to do : (3H)

**Comment by ArekHanejko** [comment]
Dokumentacja Arkadusz Hanejko: https://docs.google.com/document/d/1DYH4dDS1fmlWACQLsOgb_AOqFHzcYFFp1NSr_qXcqIk/edit?usp=sharing

**Comment by AlbertK10** [comment]
Dokumentacja Albert Kupiec:
https://docs.google.com/document/d/1cOa1Qsu35Kqs2lEwxkRS33IF1puqdj0rRI4lNKI0wWQ/edit?usp=sharing

**Comment by Kiryl21092** [comment]
Dokumentacja: https://docs.google.com/document/d/1MsAUUDaIUNuV-2C_nFGJkOejg2glgYg7v8LPpklNCJ4/edit?usp=sharing
